spring:
  profiles:
    active: prod
  application:
    name: onsaemiro
  datasource:
    url: ${secrets.DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${secrets.DB_USERNAME}
    password: ${secrets.DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0
    path: /v3/api-docs

  default-consumes-media-type: application/json
  auto-tag-classes: true
  groups:
    enabled: false

  swagger-ui:
    operationsSorter: method
    path: /swagger-ui.html

application:
  cloud:
    accessKey: ${secrets.AWS_ACCESS_KEY}
    secretAccessKey: ${secrets.AWS_SECRET_KEY}
    bucketName: ${secrets.BUCKET_NAME}