spring:
  profiles:
    active: local
  application:
    name: onsaemiro
  datasource:
    url: jdbc:mysql://onsaemiro-instance.c96ms6m44sen.ap-northeast-2.rds.amazonaws.com:3306/onsaemiro_database
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: onsaemiro_user
    password: user1234!

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0
    path: /v3/api-docs

  default-consumes-media-type: application/json
  auto-tag-classes: true
  groups:
    enabled: false

  swagger-ui:
    operationsSorter: method
    path: /swagger-ui.html